### ISSUE TITLE
Failed to list mailboxes: name 'unicode' is not defined

### ISSUE THREAD

**Issue by MederD** [masterapps-au/imap_backup#1]
line 626, in <module>
    sys.exit(main())
line 594, in main
    for m in get_account_mailboxes(config, oauth_tokens, account):
TypeError: 'NoneType' object is not iterable

**Comment by ryanbutterfield** [comment]
Hi MederD,

Just checking that you are running this script under Python 2.7? It currently only runs under Python 2. Python 3 support will be coming at a later date.

Thanks,
Ryan

**Comment by MederD** [comment]
Thanks
